package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF006c49)
val onPrimaryLight = Color(0xFFffffff)
val primaryContainerLight = Color(0xFF10b981)
val onPrimaryContainerLight = Color(0xFF00422b)
val secondaryLight = Color(0xFF006c4e)
val onSecondaryLight = Color(0xFFffffff)
val secondaryContainerLight = Color(0xFF97f5cc)
val onSecondaryContainerLight = Color(0xFF007353)
val tertiaryLight = Color(0xFF904d00)
val onTertiaryLight = Color(0xFFffffff)
val tertiaryContainerLight = Color(0xFFf08921)
val onTertiaryContainerLight = Color(0xFF5a2e00)
val errorLight = Color(0xFFba1a1a)
val onErrorLight = Color(0xFFffffff)
val errorContainerLight = Color(0xFFffdad6)
val onErrorContainerLight = Color(0xFF93000a)
val backgroundLight = Color(0xFFf9f9ff)
val onBackgroundLight = Color(0xFF111c2d)
val surfaceLight = Color(0xFFf9f9ff)
val onSurfaceLight = Color(0xFF111c2d)
val surfaceVariantLight = Color(0xFFd8e3fb)
val onSurfaceVariantLight = Color(0xFF3c4a42)
val outlineLight = Color(0xFF6c7a71)
val outlineVariantLight = Color(0xFFbbcabf)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF263143)
val inverseOnSurfaceLight = Color(0xFFecf1ff)
val inversePrimaryLight = Color(0xFF4edea3)

// Dark variants (can just use inverse or a muted version for now, but I'll generate a decent dark mode or just stick to light for both since we want it to look like the reference)
val primaryDark = Color(0xFF4edea3)
val onPrimaryDark = Color(0xFF003824)
val primaryContainerDark = Color(0xFF005236)
val onPrimaryContainerDark = Color(0xFF6ffbbe)
val secondaryDark = Color(0xFF7bd8b1)
val onSecondaryDark = Color(0xFF003827)
val secondaryContainerDark = Color(0xFF00513a)
val onSecondaryContainerDark = Color(0xFF97f5cc)
val tertiaryDark = Color(0xFFffb77d)
val onTertiaryDark = Color(0xFF4d2700)
val tertiaryContainerDark = Color(0xFF6e3900)
val onTertiaryContainerDark = Color(0xFFffdcc3)
val errorDark = Color(0xFFffb4ab)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000a)
val onErrorContainerDark = Color(0xFFffdad6)
val backgroundDark = Color(0xFF111c2d)
val onBackgroundDark = Color(0xFFe2e2e9)
val surfaceDark = Color(0xFF111c2d)
val onSurfaceDark = Color(0xFFe2e2e9)
val surfaceVariantDark = Color(0xFF404943)
val onSurfaceVariantDark = Color(0xFFbfc9c1)
val outlineDark = Color(0xFF89938c)
val outlineVariantDark = Color(0xFF404943)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFe2e2e9)
val inverseOnSurfaceDark = Color(0xFF2e3135)
val inversePrimaryDark = Color(0xFF006c49)
